stages:
  - test
  - deploy

test:
  stage: test
  script:
    - tests/homepage_exists.sh
    - tests/homepage_content.sh

deploy_staging:
  stage: deploy
  script:
    - .deploy/staging.sh
  environment:
    name: staging
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - .deploy/production.sh
  environment:
    name: production
  only:
    - master
  when: manual

